In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot  as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/content/employe (1).csv")

In [3]:
df

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent.company,workAccident,left,promotionInLast5years,dept,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.37,0.52,2,159,3,0,1,0,sales,low
4,0.41,0.50,2,153,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14994,0.11,0.85,7,275,4,0,1,0,support,medium
14995,0.99,0.83,4,274,2,0,0,0,sales,low
14996,0.72,0.72,4,175,4,0,0,0,technical,low
14997,0.24,0.91,5,177,5,0,0,0,sales,low
14998,0.77,0.83,6,271,3,0,0,0,support,low

In [4]:
df.shape

(14999, 10)

In [5]:
df.isnull().sum()

satisfactoryLevel        0
lastEvaluation           0
numberOfProjects         0
avgMonthlyHours          0
timeSpent.company        0
workAccident             0
left                     0
promotionInLast5years    0
dept                     0
salary                   0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(3008)

In [7]:
df=df.drop_duplicates(keep ='first')

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11991 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   satisfactoryLevel      11991 non-null  float64
 1   lastEvaluation         11991 non-null  float64
 2   numberOfProjects       11991 non-null  int64
 3   avgMonthlyHours        11991 non-null  int64
 4   timeSpent.company      11991 non-null  int64
 5   workAccident           11991 non-null  int64
 6   left                   11991 non-null  int64
 7   promotionInLast5years  11991 non-null  int64
 8   dept                   11991 non-null  object
 9   salary                 11991 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.0+ MB

In [10]:
#label encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [11]:
for i in df.columns:
  if df[i].dtype == 'object':
    df[i] = le.fit_transform(df[i])

/tmp/ipykernel_1009/3482075472.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i] = le.fit_transform(df[i])
/tmp/ipykernel_1009/3482075472.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i] = le.fit_transform(df[i])

In [12]:
df

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent.company,workAccident,left,promotionInLast5years,dept,salary
0,0.38,0.53,2,157,3,0,1,0,7,1
1,0.80,0.86,5,262,6,0,1,0,7,2
2,0.11,0.88,7,272,4,0,1,0,7,2
3,0.37,0.52,2,159,3,0,1,0,7,1
4,0.41,0.50,2,153,3,0,1,0,7,1
...,...,...,...,...,...,...,...,...,...,...
14992,0.30,0.88,5,245,4,0,0,0,3,1
14995,0.99,0.83,4,274,2,0,0,0,7,1
14996,0.72,0.72,4,175,4,0,0,0,9,1
14997,0.24,0.91,5,177,5,0,0,0,7,1
14998,0.77,0.83,6,271,3,0,0,0,8,1

In [13]:
le.classes_

array(['high', 'low', 'medium'], dtype=object)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11991 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   satisfactoryLevel      11991 non-null  float64
 1   lastEvaluation         11991 non-null  float64
 2   numberOfProjects       11991 non-null  int64
 3   avgMonthlyHours        11991 non-null  int64
 4   timeSpent.company      11991 non-null  int64
 5   workAccident           11991 non-null  int64
 6   left                   11991 non-null  int64
 7   promotionInLast5years  11991 non-null  int64
 8   dept                   11991 non-null  int64
 9   salary                 11991 non-null  int64
dtypes: float64(2), int64(8)
memory usage: 1.0 MB

In [ ]:
#Create a filter of data when satisfactory level is between 0 to 0.50, and time spend in the company is 2 years and also average
#monthly hours is in between 130 to 200 hrs.

In [16]:
df1=df[(df.satisfactoryLevel>=0) & (df.satisfactoryLevel<=0.50) & (df['timeSpent.company']==2) & (df.avgMonthlyHours>=130)
& (df.avgMonthlyHours<=200)]

In [17]:
df1

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent.company,workAccident,left,promotionInLast5years,dept,salary
35,0.13,0.78,6,152,2,0,1,0,8,1
379,0.48,0.78,2,198,2,0,1,0,9,2
413,0.34,0.67,4,141,2,0,1,0,7,1
1239,0.14,0.47,4,175,2,0,1,0,1,2
1426,0.19,0.58,5,182,2,0,0,0,9,2
...,...,...,...,...,...,...,...,...,...,...
14685,0.39,0.48,3,190,2,0,0,0,9,1
14835,0.50,0.90,4,171,2,0,0,0,3,1
14840,0.13,0.97,3,156,2,0,0,0,8,2
14855,0.45,0.41,3,193,2,1,0,0,7,1
14932,0.26,0.71,6,189,2,0,0,0,5,0

In [18]:
# new_df=df[(df.satisfactoryLevel>=0) & (df.satisfactoryLevel<=0.50) & (df['timeSpent.company']==2) & (df.avgMonthlyHours>=130)
# & (df.avgMonthlyHours<=200)]

In [19]:
# new_df

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent.company,workAccident,left,promotionInLast5years,dept,salary
35,0.13,0.78,6,152,2,0,1,0,8,1
379,0.48,0.78,2,198,2,0,1,0,9,2
413,0.34,0.67,4,141,2,0,1,0,7,1
1239,0.14,0.47,4,175,2,0,1,0,1,2
1426,0.19,0.58,5,182,2,0,0,0,9,2
...,...,...,...,...,...,...,...,...,...,...
14685,0.39,0.48,3,190,2,0,0,0,9,1
14835,0.50,0.90,4,171,2,0,0,0,3,1
14840,0.13,0.97,3,156,2,0,0,0,8,2
14855,0.45,0.41,3,193,2,1,0,0,7,1
14932,0.26,0.71,6,189,2,0,0,0,5,0

In [ ]:
# The average monthly hours of a employee having 2 years of experience is 167.is't it same for the employee
# having more than 2 years experience?

In [20]:
new_df = df[(df.satisfactoryLevel>=0) & (df.satisfactoryLevel<=0.50) & (df['timeSpent.company']==2) & (df.avgMonthlyHours>=130)
& (df.avgMonthlyHours<=200)]

In [21]:
proposed_mean=167

In [24]:
sample_df=new_df.sample(100,random_state=0)

In [25]:
sample_df

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent.company,workAccident,left,promotionInLast5years,dept,salary
14186,0.22,0.51,4,131,2,0,0,0,9,2
2793,0.50,0.58,4,165,2,0,0,0,7,0
11297,0.28,0.44,4,170,2,0,0,0,8,1
11752,0.48,0.99,5,180,2,0,0,0,2,1
5973,0.50,0.72,3,182,2,1,0,0,6,2
...,...,...,...,...,...,...,...,...,...,...
14685,0.39,0.48,3,190,2,0,0,0,9,1
9264,0.43,0.66,4,135,2,0,0,0,0,0
7339,0.45,0.48,3,145,2,0,0,0,8,2
4068,0.15,0.44,3,199,2,0,0,0,4,1
6378,0.50,1.00,3,149,2,0,0,0,3,2

In [ ]:
# t-test

In [26]:
from scipy.stats import ttest_1samp

In [30]:
stats,p_value=ttest_1samp(sample_df['avgMonthlyHours'],proposed_mean)

In [32]:
print(p_value)

0.6223580262972709

In [33]:
alpha=0.05
if p_value<alpha:
  print('There is a significant difference in between average monthly working hours')
else:
  print('There is no significant difference in average monthly working hours')

There is no significant difference in average monthly working hours

In [ ]:
# The percentage of employee leaving the company is 3% having experience of 2 years. is it same for the employee having more than
# 2 years of experience.

In [34]:
new_df

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent.company,workAccident,left,promotionInLast5years,dept,salary
35,0.13,0.78,6,152,2,0,1,0,8,1
379,0.48,0.78,2,198,2,0,1,0,9,2
413,0.34,0.67,4,141,2,0,1,0,7,1
1239,0.14,0.47,4,175,2,0,1,0,1,2
1426,0.19,0.58,5,182,2,0,0,0,9,2
...,...,...,...,...,...,...,...,...,...,...
14685,0.39,0.48,3,190,2,0,0,0,9,1
14835,0.50,0.90,4,171,2,0,0,0,3,1
14840,0.13,0.97,3,156,2,0,0,0,8,2
14855,0.45,0.41,3,193,2,1,0,0,7,1
14932,0.26,0.71,6,189,2,0,0,0,5,0

In [35]:
sample1=new_df.sample(100,random_state=0)

In [36]:
sample1

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent.company,workAccident,left,promotionInLast5years,dept,salary
14186,0.22,0.51,4,131,2,0,0,0,9,2
2793,0.50,0.58,4,165,2,0,0,0,7,0
11297,0.28,0.44,4,170,2,0,0,0,8,1
11752,0.48,0.99,5,180,2,0,0,0,2,1
5973,0.50,0.72,3,182,2,1,0,0,6,2
...,...,...,...,...,...,...,...,...,...,...
14685,0.39,0.48,3,190,2,0,0,0,9,1
9264,0.43,0.66,4,135,2,0,0,0,0,0
7339,0.45,0.48,3,145,2,0,0,0,8,2
4068,0.15,0.44,3,199,2,0,0,0,4,1
6378,0.50,1.00,3,149,2,0,0,0,3,2

In [37]:
count=sample1['left'].value_counts()

In [38]:
count

left
0    99
1     1
Name: count, dtype: int64

In [39]:
total=len(sample1['left'])
total

100

In [44]:
population_percentage=0.03

In [45]:
from statsmodels.stats.proportion import proportions_ztest

In [46]:
stats,p_value=proportions_ztest(count,total,population_percentage)

In [47]:
print(p_value)

3.7692144856548797e-41

In [48]:
if p_value>0.05:
  print('accept the null hypothesis')
else:
  print('reject the null hypothesis')

reject the null hypothesis

In [ ]:
# Is the mean avg monthly hours of a employee having experience of 2-5 years is the same as that of employee having experience 6-10 years?

In [ ]:
# step1 : Import required libraries.
# step2 : Create the two independent groups.
# step3 : check if both group contains data.
# step4 : Apply independent 2 sample t test
# step5 : find p_value
# step6 : Decision rule